import type { Metadata } from "next";

import { SidebarNav } from "@/components/common/Sidebar";
import { ScrollArea } from "@/components/ui/scroll-area";
export const metadata: Metadata = {
  title: "DeptEase | Dashboard",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="h-screen flex ">
      <SidebarNav />
      <div className="size-full flex flex-col">
        <ScrollArea className=" w-full flex-1 ">{children}</ScrollArea>
      </div>
    </section>
  );
}
